export const URL_CHANGED = "URL_CHANGED";
export const CALCULATING_FACES_PENDING = "CALCULATING_FACES_PENDING";
export const CALCULATING_FACES_SUCCESS = "CALCULATING_FACES_SUCCESS";
export const CALCULATING_FACES_FAILED = "CALCULATING_FACES_FAILED";
export const ROUTE_CHANGED = "ROUTE_CHANGED";
export const SIGNING_IN = "SIGNING_IN";
export const SIGN_IN_EMAIL_CHANGED = "SIGN_IN_EMAIL_CHANGED";
export const SIGN_IN_PASSWORD_CHANGED = "SIGN_IN_PASSWORD_CHANGED";
