export const URL_CHANGED = "URL_CHANGED";

export const CALCULATING_FACES_PENDING = "CALCULATING_FACES_PENDING";
export const CALCULATING_FACES_SUCCESS = "CALCULATING_FACES_SUCCESS";
export const CALCULATING_FACES_FAILED = "CALCULATING_FACES_FAILED";

export const ROUTE_CHANGED = "ROUTE_CHANGED"